# Generated by Django 4.1 on 2022-08-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_rename_customer_shippingaddress_customer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="Order",
            new_name="order",
        ),
        migrations.AlterField(
            model_name="order",
            name="date_ordered",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
